#!/usr/bin/env sh

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

# Startup Processes
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=display_added action="sleep 2 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
#yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
#yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

# Configure Yabai
yabai -m config external_bar               all:40:0     \
                window_border              on           \
                window_zoom_persist        off          \
                window_placement           second_child \
                window_topmost             off          \
                window_shadow              float        \
                window_opacity             on           \
                window_opacity_duration    0.15         \
                active_window_opacity      1.0          \
                normal_window_opacity      1.0          \
                window_border_blur         off          \
                window_border_width        2            \
                window_border_hidpi        off          \
                window_border_radius       11           \
                window_animation_duration  0.22         \
                active_window_border_color 0xffabb2bf   \
                normal_window_border_color 0xff282c34   \
                insert_feedback_color      0xff9dd274   \
                split_ratio                0.50         \
                auto_balance               off          \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                config layout              bsp          \
                window_gap                 5            \
                left_padding               5            \
                right_padding              5            \
                top_padding                5            \
                bottom_padding             5            

# Set max workspaces to 10
for idx in $(yabai -m query --spaces | jq '.[].index | select(. > 10)' | sort -nr); do
  yabai -m space --destroy "$idx"
done

# Configure Apps
yabai -m rule --add label="Obsidian" app="Obsidian" title="Obsidian" space=2
yabai -m rule --add label="Discord" app="Discord" title="Discord" space=4
yabai -m rule --add label="Spark" app="Spark" title="Spark" space=5
yabai -m rule --add label="Slack" app="Slack" title="Slack" space=5
yabai -m rule --add label="Music" app="Music" title="Music" space=6
yabai -m rule --add label="Podcasts" app="Podcasts" title="Podcasts" space=6
yabai -m rule --add label="Messages" app="Messages" title="Messages" space=7
yabai -m rule --add label="Zotero" app="Zotero" title="Zotero" space=9
yabai -m rule --add label="Zoom" app="Zoom" title="Zoom" space=10

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Vimac|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Raycast|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Box" app="^Box$" manage=off
yabai -m rule --add label="Bitwarden" manage=off
yabai -m rule --add label="Orion" app="^Orion$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advanced)$" manage=off
yabai -m rule --add label="GIMP" app="GIMP" title="GIMP" manage=off

# Get emacs to work with lsp mode (took way too long to figure out lmao
# yabai -m rule --add app="Emacs" title!="^(  —|posframe)" manage=on
# yabai -m rule --add app="Emacs" title="^  —" manage=off
# yabai -m rule --add app="Emacs" title="^posframe" manage=off

yabai -m rule --add app="Emacs" title!="^(  —|posframe|$)" manage=on
yabai -m rule --add app="Emacs" title="^  —" manage=off
yabai -m rule --add app="Emacs" title="^posframe" manage=off
yabai -m rule --add app="Emacs" title="^$" manage=off

yabai -m rule --add label="Spark" app="^Spark$" title="^(General|(Account|Team|Service|Notfication|Signature|Template|Shorcut|Folder)s|Calendar|Scheduling)$" manage=off

yabai -m rule --add label="Digital Color Meter" app="Digital Color Meter" title="Digital Color Meter" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off
yabai -m rule --add label="Autodesk Fusion 360" app="^Autodesk Fusion 360$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Proton VPN" app="Proton VPN" title="Proton VPN" manage=off

# Load emacs daemon
emacs --daemon &
