unbind C-space
set -g prefix C-space
set-option -ga terminal-overrides ",xterm-256color:Tc"

set -g base-index 1          # start with window 1
set -g pane-base-index 1     # start with pane 1
set -g renumber-windows on   # renumber windows after closing
set -g automatic-rename on   # rename the window to the current process
set -g escape-time 0         # remove esc delay
set -g mouse on              # plebs mode
set -g aggressive-resize on

# Bar
BG=#282c34
FG=#abb2bf
STATUS_SESSION_BG=#56b6c2
STATUS_WIN_NUM_BG=#61afef
STATUS_WIN_TXT_BG=#4b5263
STATUS_SEL_WIN_NUM_BG=#e06c75
STATUS_SEL_WIN_TXT_BG=#4b5263

set-option -g status-position top
set-option -g status-style fg=white,bg=$BG
set-option -g status-justify "absolute-centre"
set-option -g status-left-style none
set-option -g status-left-length "80"
set-option -g status-left "#[bg=$BG,fg=$STATUS_SESSION_BG]#[bg=$STATUS_SESSION_BG,fg=$BG]#S#[bg=$BG,fg=$STATUS_SESSION_BG]#[bg=default,fg=default] "
set -g status-right ''
set-window-option -g window-status-format "#[bg=$BG,fg=$STATUS_WIN_NUM_BG]#[bg=$STATUS_WIN_NUM_BG,fg=$BG]#I #[bg=$STATUS_WIN_TXT_BG,fg=$FG] #W#[bg=$BG,fg=$STATUS_WIN_TXT_BG]#[bg=default,fg=default]"
set-window-option -g window-status-current-format "#[bg=$BG,fg=$STATUS_SEL_WIN_NUM_BG]#[bg=$STATUS_SEL_WIN_NUM_BG,fg=$BG]#I #[bg=$STATUS_WIN_TXT_BG,fg=$FG] #W#[bg=$BG,fg=$STATUS_SEL_WIN_TXT_BG]#[bg=default,fg=default]"

# vim like bindings
bind-key h selectp -L
bind-key j selectp -D
bind-key k selectp -U
bind-key l selectp -R
bind-key -r C-h resizep -L
bind-key -r C-j resizep -D
bind-key -r C-k resizep -U
bind-key -r C-l resizep -R

bind-key s split-window -v
bind-key v split-window -h

bind-key d kill-pane

bind-key D detach

# reload config file
bind r source-file ~/.config/tmux/tmux.conf\; display-message "tmux configuration reloaded"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
